
spring:
    profiles:
        active: prod
        include: swagger
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: gsite

    thymeleaf:
        cache: true


server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

application:
    gateway:
        authorized-microservices-endpoints:
            app1: /api
            gsitemanager: /api
            gsitecustomer: /api
    http:
        version: V_1_1
        cache:
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: 8a1d3b6fa9e302c0415b6d650e9911883f953fd3
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: gsite@localhost
        base-url: http://localhost:8080
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: gsite
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false
